# Generated by Django 5.2.11 on 2026-03-06 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('slug', models.SlugField(help_text='URL de la barbería: jimbar.vercel.app/slug', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True, help_text='URL del logo')),
                ('imagen_portada', models.URLField(blank=True, help_text='URL de imagen destacada')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barbería',
                'verbose_name_plural': 'Barberías',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPERADMIN', 'Dueño del SaaS'), ('BARBERIA_ADMIN', 'Administrador de la barbería'), ('BARBERO', 'Empleado de la barbería'), ('CLIENTE', 'Cliente final')], default='CLIENTE', max_length=20)),
                ('barberia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='barberias.barberia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('TRIAL', 'Prueba (15 días)'), ('ACTIVO', 'Pagada y al día'), ('GRACIA', 'Pago vencido (3 días de gracia)'), ('SUSPENDIDO', 'Bloqueada por falta de pago')], default='TRIAL', max_length=20)),
                ('trial_hasta', models.DateTimeField(blank=True, null=True)),
                ('pagado_hasta', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('barberia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to='barberias.barberia')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
    ]
