# Generated by Django 5.2.11 on 2026-03-06 19:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barberia',
            name='imagen_portada',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sube un archivo como portada', max_length=255, null=True, verbose_name='imagen_portada'),
        ),
        migrations.AlterField(
            model_name='barberia',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Sube un archivo como logo', max_length=255, null=True, verbose_name='logo'),
        ),
    ]
