# Generated by Django 5.2.11 on 2026-03-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberias', '0002_alter_barberia_imagen_portada_alter_barberia_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberia',
            name='abre_fines_de_semana',
            field=models.BooleanField(default=True, verbose_name='¿Abre fines de semana?'),
        ),
        migrations.AddField(
            model_name='barberia',
            name='hora_apertura_finde',
            field=models.TimeField(default='10:00:00', verbose_name='Hora de apertura (S-D)'),
        ),
        migrations.AddField(
            model_name='barberia',
            name='hora_apertura_semana',
            field=models.TimeField(default='09:00:00', verbose_name='Hora de apertura (L-V)'),
        ),
        migrations.AddField(
            model_name='barberia',
            name='hora_cierre_finde',
            field=models.TimeField(default='14:00:00', verbose_name='Hora de cierre (S-D)'),
        ),
        migrations.AddField(
            model_name='barberia',
            name='hora_cierre_semana',
            field=models.TimeField(default='19:00:00', verbose_name='Hora de cierre (L-V)'),
        ),
    ]
