# Generated by Django 5.2.11 on 2026-03-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberias', '0003_barberia_abre_fines_de_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberia',
            name='estilo_trabajo',
            field=models.CharField(choices=[('PRESENCIAL', 'En local (presencial)'), ('DOMICILIO', 'A domicilio'), ('AMBOS', 'Ambos')], default='AMBOS', help_text='Modo de trabajo: solo local, solo a domicilio, o ambos.', max_length=20),
        ),
    ]
