# Generated by Django 5.2.11 on 2026-02-25 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('motivo', models.CharField(blank=True, help_text='Opcional: razón del bloqueo', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloqueo de día',
                'verbose_name_plural': 'Bloqueos de días',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField(help_text='Precio en pesos colombianos')),
                ('duracion_minutos', models.IntegerField(help_text='Duración del servicio en minutos')),
                ('activo', models.BooleanField(default=True, help_text='Si está en False, no aparece al cliente')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=150)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('cliente_correo', models.EmailField(max_length=254)),
                ('cliente_direccion', models.TextField(help_text='Dirección donde el barbero va a atender')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, help_text='Indicaciones especiales del cliente')),
                ('usuario', models.ForeignKey(blank=True, help_text='Si el cliente tiene cuenta, se vincula aquí. Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='citas.servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora_inicio'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado__in', ['RECHAZADA', 'CANCELADA']), _negated=True), fields=('fecha', 'hora_inicio'), name='unique_cita_activa_por_horario')],
            },
        ),
    ]
