# Generated by Django 5.2.11 on 2026-03-06 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberias', '0001_initial'),
        ('citas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cita',
            name='unique_cita_activa_por_horario',
        ),
        migrations.AddField(
            model_name='bloqueodia',
            name='barberia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='barberias.barberia'),
        ),
        migrations.AddField(
            model_name='cita',
            name='barberia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citas_lista', to='barberias.barberia'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='barberia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='barberias.barberia'),
        ),
        migrations.AlterField(
            model_name='bloqueodia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='bloqueodia',
            constraint=models.UniqueConstraint(fields=('fecha', 'barberia'), name='unique_bloqueo_por_barberia'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['RECHAZADA', 'CANCELADA']), _negated=True), fields=('fecha', 'hora_inicio', 'barberia'), name='unique_cita_activa_por_horario'),
        ),
    ]
