# Generated by Django 5.2.11 on 2026-03-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_remove_cita_unique_cita_activa_por_horario_and_more'),
    ]

    operations = [
    ]
