# Generated by Django 5.2.11 on 2026-03-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_auto_20260306_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cita',
            name='servicios',
            field=models.ManyToManyField(related_name='citas', to='citas.servicio'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='icono',
            field=models.CharField(blank=True, help_text='Nombre del icono Lucide (ej: scissors, user, star)', max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
