# Generated by Django 5.2.11 on 2026-03-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_remove_cita_servicio_cita_servicios_servicio_icono_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente_direccion',
            field=models.TextField(blank=True, help_text='Dirección (obligatoria solo si la barbería atiende a domicilio)'),
        ),
    ]
